### ISSUE TITLE
Comparison with Wireless Insite

### ISSUE THREAD

**Issue by hasantahir** [Swiss-Armed-Forces/openburst#3]
Hi @z-mathews 

Not related to the JOSS Review.

As someone who has heavily used Wireless Insite to observe electromagnetic scattering in a built-up region that was also imported from Open Street Map, I wanted to seek your thoughts on openburst being used in built environment in the context of cellular communication coverage.

Thanks,
Hasan

**Comment by z-mathews** [comment]
@hasantahir an earlier version of openBurst was extended with a new PCL module by a student project in a few months. The modular design helps performing such extensions without affecting existing modules. We would be happy to see if we can support the student with the cellular coverage module extension. Cheers.
